// 食物营养数据库
const foodsData = [
    // 谷物类
    {
        id: 1,
        name: "全麦面包",
        emoji: "🍞",
        category: "grains",
        calories: 247,
        protein: 13,
        carbs: 41,
        fat: 4.2,
        fiber: 7,
        description: "富含膳食纤维的全谷物面包，提供持久能量"
    },
    {
        id: 2,
        name: "燕麦片",
        emoji: "🥣",
        category: "grains",
        calories: 389,
        protein: 16.9,
        carbs: 66.3,
        fat: 6.9,
        fiber: 10.6,
        description: "营养丰富的全谷物，富含β-葡聚糖，有助于降低胆固醇"
    },
    {
        id: 3,
        name: "玉米粥",
        emoji: "🌽",
        category: "grains",
        calories: 86,
        protein: 3.2,
        carbs: 18.7,
        fat: 1.2,
        fiber: 2.7,
        description: "传统早餐选择，易于消化，适合各年龄段"
    },
    {
        id: 4,
        name: "小米粥",
        emoji: "🌾",
        category: "grains",
        calories: 119,
        protein: 4.2,
        carbs: 23.7,
        fat: 1.2,
        fiber: 1.3,
        description: "营养丰富的小米，富含B族维生素和矿物质"
    },
    {
        id: 5,
        name: "荞麦面",
        emoji: "🍜",
        category: "grains",
        calories: 343,
        protein: 13.2,
        carbs: 71.5,
        fat: 3.4,
        fiber: 10,
        description: "无麸质谷物，富含芦丁，有助于血管健康"
    },
    {
        id: 6,
        name: "糙米",
        emoji: "🍚",
        category: "grains",
        calories: 111,
        protein: 2.6,
        carbs: 23,
        fat: 0.9,
        fiber: 1.8,
        description: "保留胚芽和麸皮的完整谷物，营养更全面"
    },
    {
        id: 7,
        name: "藜麦",
        emoji: "🌱",
        category: "grains",
        calories: 120,
        protein: 4.4,
        carbs: 21.3,
        fat: 1.9,
        fiber: 2.8,
        description: "超级谷物，蛋白质含量高，含有人体所需的所有必需氨基酸"
    },
    {
        id: 8,
        name: "黑米",
        emoji: "🍚",
        category: "grains",
        calories: 340,
        protein: 8.5,
        carbs: 72.8,
        fat: 2.5,
        fiber: 3.4,
        description: "富含花青素的黑色谷物，具有抗氧化作用"
    },
    {
        id: 9,
        name: "大麦",
        emoji: "🌾",
        category: "grains",
        calories: 354,
        protein: 12.5,
        carbs: 73.5,
        fat: 2.3,
        fiber: 17.3,
        description: "富含β-葡聚糖的谷物，有助于肠道健康"
    },
    {
        id: 10,
        name: "玉米饼",
        emoji: "🌮",
        category: "grains",
        calories: 218,
        protein: 5.4,
        carbs: 44.6,
        fat: 2.9,
        fiber: 3.9,
        description: "无麸质谷物制品，适合麸质敏感人群"
    },

    // 蛋白质类
    {
        id: 11,
        name: "鸡蛋",
        emoji: "🥚",
        category: "protein",
        calories: 155,
        protein: 12.6,
        carbs: 1.1,
        fat: 10.6,
        fiber: 0,
        description: "优质蛋白质来源，富含卵磷脂和胆碱"
    },
    {
        id: 12,
        name: "鸡胸肉",
        emoji: "🍗",
        category: "protein",
        calories: 165,
        protein: 31,
        carbs: 0,
        fat: 3.6,
        fiber: 0,
        description: "低脂高蛋白的优质肉类选择"
    },
    {
        id: 13,
        name: "三文鱼",
        emoji: "🐟",
        category: "protein",
        calories: 208,
        protein: 25,
        carbs: 0,
        fat: 12,
        fiber: 0,
        description: "富含omega-3脂肪酸的深海鱼类"
    },
    {
        id: 14,
        name: "豆腐",
        emoji: "🧈",
        category: "protein",
        calories: 76,
        protein: 8.1,
        carbs: 1.9,
        fat: 4.8,
        fiber: 0.3,
        description: "植物性蛋白质来源，富含异黄酮"
    },
    {
        id: 15,
        name: "虾仁",
        emoji: "🦐",
        category: "protein",
        calories: 99,
        protein: 24,
        carbs: 0.2,
        fat: 0.3,
        fiber: 0,
        description: "低脂高蛋白的海鲜选择"
    },
    {
        id: 16,
        name: "牛肉",
        emoji: "🥩",
        category: "protein",
        calories: 250,
        protein: 26,
        carbs: 0,
        fat: 15,
        fiber: 0,
        description: "富含铁和维生素B12的优质蛋白质"
    },
    {
        id: 17,
        name: "猪肉",
        emoji: "🥓",
        category: "protein",
        calories: 242,
        protein: 27,
        carbs: 0,
        fat: 14,
        fiber: 0,
        description: "传统肉类选择，富含B族维生素"
    },
    {
        id: 18,
        name: "鸭蛋",
        emoji: "🥚",
        category: "protein",
        calories: 185,
        protein: 12.8,
        carbs: 1,
        fat: 13.8,
        fiber: 0,
        description: "比鸡蛋更大的蛋类，营养更丰富"
    },
    {
        id: 19,
        name: "鹌鹑蛋",
        emoji: "🥚",
        category: "protein",
        calories: 158,
        protein: 13.1,
        carbs: 0.4,
        fat: 11.2,
        fiber: 0,
        description: "小巧精致的蛋类，营养密度高"
    },
    {
        id: 20,
        name: "金枪鱼",
        emoji: "🐟",
        category: "protein",
        calories: 144,
        protein: 30,
        carbs: 0,
        fat: 1,
        fiber: 0,
        description: "低脂高蛋白的鱼类，富含硒"
    },

    // 乳制品类
    {
        id: 21,
        name: "牛奶",
        emoji: "🥛",
        category: "dairy",
        calories: 42,
        protein: 3.4,
        carbs: 5,
        fat: 1,
        fiber: 0,
        description: "富含钙和维生素D的基础乳制品"
    },
    {
        id: 22,
        name: "酸奶",
        emoji: "🍶",
        category: "dairy",
        calories: 59,
        protein: 10,
        carbs: 3.6,
        fat: 0.4,
        fiber: 0,
        description: "富含益生菌的发酵乳制品"
    },
    {
        id: 23,
        name: "奶酪",
        emoji: "🧀",
        category: "dairy",
        calories: 113,
        protein: 7,
        carbs: 0.4,
        fat: 9,
        fiber: 0,
        description: "浓缩的乳制品，钙含量丰富"
    },
    {
        id: 24,
        name: "黄油",
        emoji: "🧈",
        category: "dairy",
        calories: 717,
        protein: 0.9,
        carbs: 0.1,
        fat: 81,
        fiber: 0,
        description: "高脂肪乳制品，提供丰富能量"
    },
    {
        id: 25,
        name: "奶油",
        emoji: "🥛",
        category: "dairy",
        calories: 340,
        protein: 2.1,
        carbs: 2.8,
        fat: 36,
        fiber: 0,
        description: "高脂肪乳制品，常用于烹饪"
    },
    {
        id: 26,
        name: "羊奶",
        emoji: "🐐",
        category: "dairy",
        calories: 69,
        protein: 3.6,
        carbs: 4.5,
        fat: 4.1,
        fiber: 0,
        description: "比牛奶更易消化的乳制品选择"
    },
    {
        id: 27,
        name: "马苏里拉奶酪",
        emoji: "🧀",
        category: "dairy",
        calories: 280,
        protein: 28,
        carbs: 2.2,
        fat: 17,
        fiber: 0,
        description: "意大利传统奶酪，蛋白质含量高"
    },
    {
        id: 28,
        name: "希腊酸奶",
        emoji: "🍶",
        category: "dairy",
        calories: 59,
        protein: 10,
        carbs: 3.6,
        fat: 0.4,
        fiber: 0,
        description: "过滤浓缩的酸奶，蛋白质含量更高"
    },
    {
        id: 29,
        name: "酸奶油",
        emoji: "🥛",
        category: "dairy",
        calories: 198,
        protein: 2.4,
        carbs: 4.3,
        fat: 19,
        fiber: 0,
        description: "发酵的奶油制品，口感丰富"
    },
    {
        id: 30,
        name: "炼乳",
        emoji: "🥛",
        category: "dairy",
        calories: 321,
        protein: 7.9,
        carbs: 54.4,
        fat: 8.7,
        fiber: 0,
        description: "浓缩的甜味乳制品"
    },

    // 水果类
    {
        id: 31,
        name: "苹果",
        emoji: "🍎",
        category: "fruits",
        calories: 52,
        protein: 0.3,
        carbs: 14,
        fat: 0.2,
        fiber: 2.4,
        description: "富含果胶和抗氧化物质的水果"
    },
    {
        id: 32,
        name: "香蕉",
        emoji: "🍌",
        category: "fruits",
        calories: 89,
        protein: 1.1,
        carbs: 23,
        fat: 0.3,
        fiber: 2.6,
        description: "富含钾和维生素B6的水果"
    },
    {
        id: 33,
        name: "橙子",
        emoji: "🍊",
        category: "fruits",
        calories: 47,
        protein: 0.9,
        carbs: 12,
        fat: 0.1,
        fiber: 2.4,
        description: "富含维生素C的柑橘类水果"
    },
    {
        id: 34,
        name: "草莓",
        emoji: "🍓",
        category: "fruits",
        calories: 32,
        protein: 0.7,
        carbs: 8,
        fat: 0.3,
        fiber: 2,
        description: "富含维生素C和花青素的浆果"
    },
    {
        id: 35,
        name: "蓝莓",
        emoji: "🫐",
        category: "fruits",
        calories: 57,
        protein: 0.7,
        carbs: 14,
        fat: 0.3,
        fiber: 2.4,
        description: "超级水果，富含抗氧化物质"
    },
    {
        id: 36,
        name: "葡萄",
        emoji: "🍇",
        category: "fruits",
        calories: 62,
        protein: 0.6,
        carbs: 16,
        fat: 0.2,
        fiber: 0.9,
        description: "富含白藜芦醇的葡萄类水果"
    },
    {
        id: 37,
        name: "猕猴桃",
        emoji: "🥝",
        category: "fruits",
        calories: 61,
        protein: 1.1,
        carbs: 15,
        fat: 0.5,
        fiber: 3,
        description: "维生素C含量极高的水果"
    },
    {
        id: 38,
        name: "芒果",
        emoji: "🥭",
        category: "fruits",
        calories: 60,
        protein: 0.8,
        carbs: 15,
        fat: 0.4,
        fiber: 1.6,
        description: "富含β-胡萝卜素的热带水果"
    },
    {
        id: 39,
        name: "菠萝",
        emoji: "🍍",
        category: "fruits",
        calories: 50,
        protein: 0.5,
        carbs: 13,
        fat: 0.1,
        fiber: 1.4,
        description: "富含菠萝蛋白酶的水果"
    },
    {
        id: 40,
        name: "梨",
        emoji: "🍐",
        category: "fruits",
        calories: 57,
        protein: 0.4,
        carbs: 15,
        fat: 0.1,
        fiber: 3.1,
        description: "富含膳食纤维的水果"
    },

    // 蔬菜类
    {
        id: 41,
        name: "菠菜",
        emoji: "🥬",
        category: "vegetables",
        calories: 23,
        protein: 2.9,
        carbs: 3.6,
        fat: 0.4,
        fiber: 2.2,
        description: "富含铁和叶酸的绿叶蔬菜"
    },
    {
        id: 42,
        name: "胡萝卜",
        emoji: "🥕",
        category: "vegetables",
        calories: 41,
        protein: 0.9,
        carbs: 10,
        fat: 0.2,
        fiber: 2.8,
        description: "富含β-胡萝卜素的根茎类蔬菜"
    },
    {
        id: 43,
        name: "西兰花",
        emoji: "🥦",
        category: "vegetables",
        calories: 34,
        protein: 2.8,
        carbs: 7,
        fat: 0.4,
        fiber: 2.6,
        description: "富含维生素C和硫代葡萄糖苷的十字花科蔬菜"
    },
    {
        id: 44,
        name: "番茄",
        emoji: "🍅",
        category: "vegetables",
        calories: 18,
        protein: 0.9,
        carbs: 3.9,
        fat: 0.2,
        fiber: 1.2,
        description: "富含番茄红素的茄科蔬菜"
    },
    {
        id: 45,
        name: "黄瓜",
        emoji: "🥒",
        category: "vegetables",
        calories: 16,
        protein: 0.7,
        carbs: 3.6,
        fat: 0.1,
        fiber: 0.5,
        description: "低热量高水分的瓜类蔬菜"
    },
    {
        id: 46,
        name: "洋葱",
        emoji: "🧅",
        category: "vegetables",
        calories: 40,
        protein: 1.1,
        carbs: 9,
        fat: 0.1,
        fiber: 1.7,
        description: "富含槲皮素的葱属蔬菜"
    },
    {
        id: 47,
        name: "大蒜",
        emoji: "🧄",
        category: "vegetables",
        calories: 149,
        protein: 6.4,
        carbs: 33,
        fat: 0.5,
        fiber: 2.1,
        description: "富含大蒜素的调味蔬菜"
    },
    {
        id: 48,
        name: "青椒",
        emoji: "🫑",
        category: "vegetables",
        calories: 20,
        protein: 0.9,
        carbs: 4.6,
        fat: 0.2,
        fiber: 1.7,
        description: "富含维生素C的茄科蔬菜"
    },
    {
        id: 49,
        name: "南瓜",
        emoji: "🎃",
        category: "vegetables",
        calories: 26,
        protein: 1,
        carbs: 6.5,
        fat: 0.1,
        fiber: 0.5,
        description: "富含β-胡萝卜素的瓜类蔬菜"
    },
    {
        id: 50,
        name: "土豆",
        emoji: "🥔",
        category: "vegetables",
        calories: 77,
        protein: 2,
        carbs: 17,
        fat: 0.1,
        fiber: 2.2,
        description: "富含钾和维生素C的根茎类蔬菜"
    },

    // 坚果类
    {
        id: 51,
        name: "核桃",
        emoji: "🌰",
        category: "nuts",
        calories: 654,
        protein: 15,
        carbs: 14,
        fat: 65,
        fiber: 6.7,
        description: "富含omega-3脂肪酸的坚果"
    },
    {
        id: 52,
        name: "杏仁",
        emoji: "🥜",
        category: "nuts",
        calories: 579,
        protein: 21,
        carbs: 22,
        fat: 50,
        fiber: 12.5,
        description: "富含维生素E和膳食纤维的坚果"
    },
    {
        id: 53,
        name: "花生",
        emoji: "🥜",
        category: "nuts",
        calories: 567,
        protein: 26,
        carbs: 16,
        fat: 49,
        fiber: 8.5,
        description: "富含蛋白质和健康脂肪的坚果"
    },
    {
        id: 54,
        name: "腰果",
        emoji: "🥜",
        category: "nuts",
        calories: 553,
        protein: 18,
        carbs: 30,
        fat: 44,
        fiber: 3.3,
        description: "富含镁和锌的坚果"
    },
    {
        id: 55,
        name: "开心果",
        emoji: "🥜",
        category: "nuts",
        calories: 560,
        protein: 20,
        carbs: 28,
        fat: 45,
        fiber: 10.6,
        description: "富含叶黄素和玉米黄质的坚果"
    },
    {
        id: 56,
        name: "榛子",
        emoji: "🌰",
        category: "nuts",
        calories: 628,
        protein: 15,
        carbs: 17,
        fat: 61,
        fiber: 9.7,
        description: "富含维生素E和锰的坚果"
    },
    {
        id: 57,
        name: "松子",
        emoji: "🌰",
        category: "nuts",
        calories: 673,
        protein: 14,
        carbs: 13,
        fat: 68,
        fiber: 3.7,
        description: "富含锌和维生素K的坚果"
    },
    {
        id: 58,
        name: "夏威夷果",
        emoji: "🥜",
        category: "nuts",
        calories: 718,
        protein: 8,
        carbs: 14,
        fat: 76,
        fiber: 8.6,
        description: "富含单不饱和脂肪酸的坚果"
    },
    {
        id: 59,
        name: "巴西坚果",
        emoji: "🥜",
        category: "nuts",
        calories: 656,
        protein: 14,
        carbs: 12,
        fat: 66,
        fiber: 7.5,
        description: "富含硒的坚果"
    },
    {
        id: 60,
        name: "葵花籽",
        emoji: "🌻",
        category: "nuts",
        calories: 584,
        protein: 21,
        carbs: 20,
        fat: 51,
        fiber: 8.6,
        description: "富含维生素E和叶酸的种子"
    },

    // 饮品类
    {
        id: 61,
        name: "豆浆",
        emoji: "🥛",
        category: "drinks",
        calories: 31,
        protein: 2.9,
        carbs: 2.8,
        fat: 1.5,
        fiber: 0.3,
        description: "植物性蛋白质饮品，富含异黄酮"
    },
    {
        id: 62,
        name: "橙汁",
        emoji: "🍊",
        category: "drinks",
        calories: 45,
        protein: 0.7,
        carbs: 10.4,
        fat: 0.2,
        fiber: 0.2,
        description: "富含维生素C的果汁"
    },
    {
        id: 63,
        name: "苹果汁",
        emoji: "🍎",
        category: "drinks",
        calories: 46,
        protein: 0.1,
        carbs: 11.3,
        fat: 0.1,
        fiber: 0.2,
        description: "富含多酚类物质的果汁"
    },
    {
        id: 64,
        name: "绿茶",
        emoji: "🍵",
        category: "drinks",
        calories: 1,
        protein: 0.2,
        carbs: 0.2,
        fat: 0,
        fiber: 0,
        description: "富含儿茶素的健康饮品"
    },
    {
        id: 65,
        name: "咖啡",
        emoji: "☕",
        category: "drinks",
        calories: 2,
        protein: 0.3,
        carbs: 0,
        fat: 0,
        fiber: 0,
        description: "富含咖啡因的提神饮品"
    },
    {
        id: 66,
        name: "蜂蜜水",
        emoji: "🍯",
        category: "drinks",
        calories: 64,
        protein: 0.1,
        carbs: 17.3,
        fat: 0,
        fiber: 0,
        description: "天然甜味饮品，具有抗菌作用"
    },
    {
        id: 67,
        name: "柠檬水",
        emoji: "🍋",
        category: "drinks",
        calories: 29,
        protein: 0.4,
        carbs: 9.3,
        fat: 0.3,
        fiber: 0.3,
        description: "富含维生素C的清爽饮品"
    },
    {
        id: 68,
        name: "椰子水",
        emoji: "🥥",
        category: "drinks",
        calories: 19,
        protein: 0.7,
        carbs: 3.7,
        fat: 0.2,
        fiber: 1.1,
        description: "天然电解质饮品"
    },
    {
        id: 69,
        name: "蔓越莓汁",
        emoji: "🫐",
        category: "drinks",
        calories: 54,
        protein: 0.4,
        carbs: 13.5,
        fat: 0.1,
        fiber: 0.1,
        description: "富含原花青素的果汁"
    },
    {
        id: 70,
        name: "葡萄汁",
        emoji: "🍇",
        category: "drinks",
        calories: 71,
        protein: 0.4,
        carbs: 17.3,
        fat: 0.1,
        fiber: 0.2,
        description: "富含白藜芦醇的果汁"
    },

    // 更多谷物类
    {
        id: 71,
        name: "糯米",
        emoji: "🍚",
        category: "grains",
        calories: 116,
        protein: 2.6,
        carbs: 25.6,
        fat: 0.2,
        fiber: 0.4,
        description: "粘性较强的米类，适合制作甜点"
    },
    {
        id: 72,
        name: "薏米",
        emoji: "🌾",
        category: "grains",
        calories: 357,
        protein: 12.7,
        carbs: 71.1,
        fat: 6.5,
        fiber: 3.2,
        description: "传统药食同源的谷物"
    },
    {
        id: 73,
        name: "绿豆",
        emoji: "🫘",
        category: "grains",
        calories: 105,
        protein: 7.9,
        carbs: 19.2,
        fat: 0.4,
        fiber: 7.6,
        description: "富含蛋白质的豆类谷物"
    },
    {
        id: 74,
        name: "红豆",
        emoji: "🫘",
        category: "grains",
        calories: 127,
        protein: 8.7,
        carbs: 23.4,
        fat: 0.5,
        fiber: 7.3,
        description: "富含铁和膳食纤维的豆类"
    },
    {
        id: 75,
        name: "黑豆",
        emoji: "🫘",
        category: "grains",
        calories: 132,
        protein: 8.9,
        carbs: 23.7,
        fat: 0.5,
        fiber: 8.7,
        description: "富含花青素的黑色豆类"
    },

    // 更多蛋白质类
    {
        id: 76,
        name: "带鱼",
        emoji: "🐟",
        category: "protein",
        calories: 144,
        protein: 20.4,
        carbs: 0,
        fat: 6.8,
        fiber: 0,
        description: "富含DHA的深海鱼类"
    },
    {
        id: 77,
        name: "鲈鱼",
        emoji: "🐟",
        category: "protein",
        calories: 97,
        protein: 18.6,
        carbs: 0,
        fat: 2.3,
        fiber: 0,
        description: "肉质鲜嫩的淡水鱼类"
    },
    {
        id: 78,
        name: "鱿鱼",
        emoji: "🦑",
        category: "protein",
        calories: 92,
        protein: 15.6,
        carbs: 3.1,
        fat: 1.4,
        fiber: 0,
        description: "富含牛磺酸的海鲜"
    },
    {
        id: 79,
        name: "扇贝",
        emoji: "🦪",
        category: "protein",
        calories: 69,
        protein: 12.1,
        carbs: 3.4,
        fat: 0.5,
        fiber: 0,
        description: "富含锌和维生素B12的海鲜"
    },
    {
        id: 80,
        name: "海参",
        emoji: "🦪",
        category: "protein",
        calories: 85,
        protein: 13.2,
        carbs: 0.9,
        fat: 0.3,
        fiber: 0,
        description: "传统滋补海产品"
    },

    // 更多水果类
    {
        id: 81,
        name: "石榴",
        emoji: "🍎",
        category: "fruits",
        calories: 83,
        protein: 1.7,
        carbs: 19,
        fat: 1.2,
        fiber: 4,
        description: "富含花青素和鞣花酸的水果"
    },
    {
        id: 82,
        name: "无花果",
        emoji: "🍎",
        category: "fruits",
        calories: 74,
        protein: 0.8,
        carbs: 19,
        fat: 0.3,
        fiber: 2.9,
        description: "富含膳食纤维的水果"
    },
    {
        id: 83,
        name: "柿子",
        emoji: "🍅",
        category: "fruits",
        calories: 70,
        protein: 0.6,
        carbs: 18.6,
        fat: 0.2,
        fiber: 3.6,
        description: "富含维生素A的水果"
    },
    {
        id: 84,
        name: "山楂",
        emoji: "🍎",
        category: "fruits",
        calories: 95,
        protein: 0.5,
        carbs: 25,
        fat: 0.3,
        fiber: 3.1,
        description: "富含山楂酸的水果"
    },
    {
        id: 85,
        name: "柚子",
        emoji: "🍊",
        category: "fruits",
        calories: 42,
        protein: 0.8,
        carbs: 10.6,
        fat: 0.2,
        fiber: 1.8,
        description: "富含维生素C的柑橘类水果"
    },

    // 更多蔬菜类
    {
        id: 86,
        name: "芹菜",
        emoji: "🥬",
        category: "vegetables",
        calories: 16,
        protein: 0.7,
        carbs: 3,
        fat: 0.2,
        fiber: 1.6,
        description: "富含芹菜素的绿叶蔬菜"
    },
    {
        id: 87,
        name: "韭菜",
        emoji: "🥬",
        category: "vegetables",
        calories: 32,
        protein: 2.9,
        carbs: 6.5,
        fat: 0.2,
        fiber: 2.8,
        description: "富含硫化合物的葱属蔬菜"
    },
    {
        id: 88,
        name: "茼蒿",
        emoji: "🥬",
        category: "vegetables",
        calories: 24,
        protein: 3.4,
        carbs: 3.7,
        fat: 0.3,
        fiber: 3.2,
        description: "富含胡萝卜素的绿叶蔬菜"
    },
    {
        id: 89,
        name: "芥菜",
        emoji: "🥬",
        category: "vegetables",
        calories: 27,
        protein: 2.9,
        carbs: 4.7,
        fat: 0.4,
        fiber: 3.2,
        description: "富含芥子油苷的十字花科蔬菜"
    },
    {
        id: 90,
        name: "苋菜",
        emoji: "🥬",
        category: "vegetables",
        calories: 23,
        protein: 2.5,
        carbs: 4,
        fat: 0.3,
        fiber: 2.1,
        description: "富含钙和铁的绿叶蔬菜"
    },

    // 更多饮品类
    {
        id: 91,
        name: "红枣水",
        emoji: "🍯",
        category: "drinks",
        calories: 79,
        protein: 1.2,
        carbs: 20.5,
        fat: 0.2,
        fiber: 1.1,
        description: "传统滋补饮品"
    },
    {
        id: 92,
        name: "姜茶",
        emoji: "🍵",
        category: "drinks",
        calories: 4,
        protein: 0.1,
        carbs: 0.9,
        fat: 0,
        fiber: 0.1,
        description: "富含姜辣素的温热饮品"
    },
    {
        id: 93,
        name: "薄荷茶",
        emoji: "🍵",
        category: "drinks",
        calories: 1,
        protein: 0.1,
        carbs: 0.2,
        fat: 0,
        fiber: 0,
        description: "清爽提神的草本茶"
    },
    {
        id: 94,
        name: "玫瑰花茶",
        emoji: "🌹",
        category: "drinks",
        calories: 1,
        protein: 0.1,
        carbs: 0.2,
        fat: 0,
        fiber: 0,
        description: "富含花青素的芳香茶"
    },
    {
        id: 95,
        name: "菊花茶",
        emoji: "🌼",
        category: "drinks",
        calories: 1,
        protein: 0.1,
        carbs: 0.2,
        fat: 0,
        fiber: 0,
        description: "传统清热饮品"
    },

    // 最后几个食物
    {
        id: 96,
        name: "芝麻",
        emoji: "⚪",
        category: "nuts",
        calories: 573,
        protein: 18,
        carbs: 23,
        fat: 50,
        fiber: 11.8,
        description: "富含钙和芝麻素的种子"
    },
    {
        id: 97,
        name: "亚麻籽",
        emoji: "🌱",
        category: "nuts",
        calories: 534,
        protein: 18,
        carbs: 29,
        fat: 42,
        fiber: 27.3,
        description: "富含omega-3脂肪酸的种子"
    },
    {
        id: 98,
        name: "奇亚籽",
        emoji: "🌱",
        category: "nuts",
        calories: 486,
        protein: 17,
        carbs: 42,
        fat: 31,
        fiber: 34.4,
        description: "富含膳食纤维和omega-3的超级种子"
    },
    {
        id: 99,
        name: "南瓜籽",
        emoji: "🎃",
        category: "nuts",
        calories: 559,
        protein: 19,
        carbs: 54,
        fat: 19,
        fiber: 18.4,
        description: "富含锌和镁的种子"
    },
    {
        id: 100,
        name: "葵花籽油",
        emoji: "🌻",
        category: "nuts",
        calories: 884,
        protein: 0,
        carbs: 0,
        fat: 100,
        fiber: 0,
        description: "富含维生素E的植物油"
    }
];

// 游戏关卡数据
const gameLevels = [
    {
        level: 1,
        targets: {
            calories: { min: 300, max: 400 },
            protein: { min: 15, max: 25 },
            carbs: { min: 40, max: 60 },
            fat: { min: 8, max: 15 },
            fiber: { min: 5, max: 10 }
        },
        timeLimit: 60,
        description: "初级营养师：完成基础营养搭配"
    },
    {
        level: 2,
        targets: {
            calories: { min: 350, max: 450 },
            protein: { min: 20, max: 30 },
            carbs: { min: 45, max: 65 },
            fat: { min: 10, max: 18 },
            fiber: { min: 8, max: 15 }
        },
        timeLimit: 55,
        description: "中级营养师：平衡营养搭配"
    },
    {
        level: 3,
        targets: {
            calories: { min: 400, max: 500 },
            protein: { min: 25, max: 35 },
            carbs: { min: 50, max: 70 },
            fat: { min: 12, max: 20 },
            fiber: { min: 10, max: 18 }
        },
        timeLimit: 50,
        description: "高级营养师：精确营养控制"
    },
    {
        level: 4,
        targets: {
            calories: { min: 450, max: 550 },
            protein: { min: 30, max: 40 },
            carbs: { min: 55, max: 75 },
            fat: { min: 15, max: 25 },
            fiber: { min: 12, max: 20 }
        },
        timeLimit: 45,
        description: "营养专家：复杂营养目标"
    },
    {
        level: 5,
        targets: {
            calories: { min: 500, max: 600 },
            protein: { min: 35, max: 45 },
            carbs: { min: 60, max: 80 },
            fat: { min: 18, max: 28 },
            fiber: { min: 15, max: 25 }
        },
        timeLimit: 40,
        description: "营养大师：完美营养平衡"
    }
];

// 营养建议数据
const nutritionAdvice = {
    lowCalories: "热量偏低，建议增加一些高能量食物如坚果或全谷物",
    highCalories: "热量偏高，建议减少高脂肪食物，增加蔬菜水果",
    lowProtein: "蛋白质不足，建议增加鸡蛋、豆制品或瘦肉",
    highProtein: "蛋白质充足，搭配合理",
    lowCarbs: "碳水化合物不足，建议增加全谷物或水果",
    highCarbs: "碳水化合物偏高，建议减少精制谷物",
    lowFat: "脂肪含量偏低，可适量增加健康脂肪如坚果",
    highFat: "脂肪含量偏高，建议减少高脂肪食物",
    lowFiber: "膳食纤维不足，建议增加蔬菜、水果和全谷物",
    highFiber: "膳食纤维充足，有助于肠道健康",
    balanced: "营养搭配均衡，是理想的早餐选择！",
    perfect: "完美搭配！营养全面且均衡，为一天提供充足能量。"
}; 